steps:

# Build the new docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest', '.']

# Run the app and dependencies in the background using docker-compose.
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'

# Push the new image to the registry.
images: ['gcr.io/$PROJECT_ID/gcb-docker-compose:latest']